from telethon.sessions import StringSession
from telethon.sync import TelegramClient

print("")
print("""Hey! Welcome to [EliteBot](https://t.me/ELITES_OFFICIAL)This String Session Generated By This [Person](https://t.me/THEDEVANSHOP)""")
print("""Kindly Enter Your Details To Continue ! """)

API_KEY = input("API_KEY: ")
API_HASH = input("API_HASH: ")

while True:
    try:
        with TelegramClient(StringSession(), API_KEY, API_HASH) as client:
            print("Your String Session is Sent To Your Saved Message, Store It To A Safe Place!! ")
            print("")
            session = client.session.save()
            client.send_message(
                "me",
                f"Hey! Here is your string session \n\n (Tap on it to copy) \n\n `{session}` \n\n If Having Any Problem Then Ask [Here](https://t.me/ELITES_SUPPPORT)",
            )

            print(
                "Thanks for Choosing EliteBot Have A Good Time....Note That When You Terminate the Old Session ComeBack And Genrate A New String Session Old One Wont Work"
            )
    except:
        print("")
        print(
            "Wrong phone number \n make sure its with correct country code. Example : +919961998999 ! Kindly Retry"
        )
        print("")
        continue
    break
